изменения, выполненные в соответствии с ТЗ: изменен интерфейс History…
EvgenEng/newrepo-java-kanban pull request #4
Opened 2024-12-27 21:22 UTC by EvgenEng

…Manadger, выполнена реализация inmemoryhistorymanager с использованием двусвязного списка хэшмап, обновлен класс  inmemorytaskmanager, добавлен тест

# Conflicts:
#	.idea/vcs.xml
#	src/interfaces/HistoryManager.java
#	src/manager/InMemoryHistoryManager.java
#	src/manager/InMemoryTaskManager.java
#	src/manager/Managers.java
#	src/task/Epic.java
#	src/task/Task.java
#	src/tests/HistoryManagerTest.java

2024-12-31 17:15 UTC, afomkina requested changes

2024-12-31 17:15 UTC, afomkina commented on .idea/.name
Сейчас в работе есть лишние файлы, которые генерируются средой разработки, чтобы от них избавиться в данный файл нужно добавить следующие строки:

```
.idea
*.iml
```

Затем нужно будет удалить лишние папки `.idea` и все `.iml` файлы из проекта.
Останется только закоммитить изменения

2024-12-31 17:15 UTC, afomkina commented on src/manager/InMemoryHistoryManager.java
> +        Task task;
У полей класса должны быть модификаторы доступа

2024-12-31 17:15 UTC, afomkina commented on src/manager/InMemoryHistoryManager.java
> +
Лишний отступ

2024-12-31 17:15 UTC, afomkina commented on src/task/Epic.java
> +
Лишний отступ

2024-12-31 17:15 UTC, afomkina commented on src/task/Epic.java
> +
Лишний отступ

2024-12-31 17:15 UTC, afomkina commented on src/task/Epic.java
> +
Лишний отступ

2024-12-31 17:15 UTC, afomkina commented on src/manager/Managers.java
> +
Лишний отступ

2024-12-31 17:15 UTC, afomkina commented on src/manager/Managers.java
> +
Лишний отступ

2024-12-31 17:15 UTC, afomkina commented on src/manager/InMemoryTaskManager.java
> +
Поправь лишние отсутпы после override

2024-12-31 17:15 UTC, afomkina commented on src/interfaces/HistoryManager.java
> +    void remove(int id); // Удаляет задачу из истории по ID
Метод нужно использовать в методах удаления задач в менеджере задач

2025-01-01 19:48 UTC, afomkina requested changes
Нужно проверить, что история правильно удаляет задачи, так как сейчас не проходит [тест](https://github.com/EvgenEng/newrepo-java-kanban/actions/runs/12562748701/job/35023637335?pr=4)

2025-01-20 15:55 UTC, afomkina requested changes

2025-01-20 15:55 UTC, afomkina commented on java-kanban2.iml
Этот файл нужно удалить

2025-01-20 15:55 UTC, afomkina commented on .idea/.name
Папку .idea нужно удалить

2025-01-20 15:55 UTC, afomkina commented on src/manager/InMemoryHistoryManager.java
> +        private Task task;
Поле должно быть `final`

2025-01-20 15:55 UTC, afomkina commented on test/EpicTest.java
Нужно удалить одну из папок с тестами. Пусть это будет `tests`, которую мы создали ранее. Должна остаться только эта

2025-01-20 15:55 UTC, afomkina commented on test/tests.txt
Этот файл лишний - его нужно удалить

2025-01-20 17:17 UTC, EvgenEng commented on java-kanban2.iml
Я не могу удалить данный файл, т.к. код снова слетает. Но зато могу избавиться от второго файла, который уже по видимому не нужен - java-kanban.iml. Его я удалю

2025-01-21 10:59 UTC, afomkina requested changes

2025-01-21 10:59 UTC, afomkina commented on java-kanban2.iml
Этот файл нужно удалить

2025-01-21 10:59 UTC, afomkina commented on tests.txt
Этот файл нужно удалить

2025-01-22 10:42 UTC, afomkina approved these changes

2025-01-22 19:24 UTC, merged